-- =====================================================================
-- pail — SCHEMA-SYNC.sql
-- =====================================================================
-- WHAT THIS IS
--   A faithful, idempotent reproduction of the CURRENT LIVE schema for
--   pail's tables in the shared Supabase project "Kura"
--   (project_id: lrbmtcyhqzuyczovajnj).
--
--   Generated by introspecting the live Kura database on 2026-07-18.
--
-- WHY IT EXISTS
--   Schema changes were made directly in the Supabase SQL Editor over time
--   and were never written back into this repo. This file closes that gap:
--   it is what you run to recreate pail's database from scratch.
--
-- ⚠️  MIGRATION.sql IN THIS REPO IS OUTDATED — DO NOT USE IT FOR A FRESH
--     DEPLOY. It targets a table named `items`. That table was renamed to
--     `pail_items` live (all app code — page.tsx, AddItemModal,
--     ItemDetailModal — queries `pail_items`), and the rename was never
--     written back. There is no `items` table in the live database.
--     MIGRATION.sql is retained only as historical record; THIS FILE
--     reflects reality.
--
-- PROPERTIES
--   * Additive only. No DROP TABLE, no DROP COLUMN, no data changes.
--   * Fully idempotent — safe to run repeatedly. Against the existing live
--     database it is a complete no-op.
--   * Schema only. Contains no seed data and no user data.
--   * Statements are ordered to satisfy dependencies.
--
-- NOTE ON RLS
--   pail has no auth. The app uses the anon key for both reads AND writes,
--   so live carries a permissive "anon write" ALL policy. That is intentional
--   for this app; it is reproduced below exactly as it exists live.
-- =====================================================================


-- ---------------------------------------------------------------------
-- 1. TABLE: pail_items
--    The single table backing the entire app.
-- ---------------------------------------------------------------------

create table if not exists public.pail_items (
  id            uuid        primary key default gen_random_uuid(),
  title         text        not null,
  category      text        not null,
  time_window   text,
  status        text        not null default 'someday',
  notes         text,
  added_by      text,
  completed_by  text,
  completed_at  timestamptz,
  memory_photo  text,
  memory_note   text,
  created_at    timestamptz not null default now(),
  seasons       text[]      not null default '{}',
  date_start    date,
  date_end      date,
  months        text[]      not null default '{}'
);


-- ---------------------------------------------------------------------
-- 2. COLUMNS (idempotent top-up for a pre-existing pail_items)
--    Columns are added without NOT NULL here so this is safe against a
--    populated table; the NOT NULL enforcement block below applies the
--    constraint only when the existing data permits it.
-- ---------------------------------------------------------------------

alter table public.pail_items add column if not exists title        text;
alter table public.pail_items add column if not exists category     text;
alter table public.pail_items add column if not exists time_window  text;
alter table public.pail_items add column if not exists status       text default 'someday';
alter table public.pail_items add column if not exists notes        text;
alter table public.pail_items add column if not exists added_by     text;
alter table public.pail_items add column if not exists completed_by text;
alter table public.pail_items add column if not exists completed_at timestamptz;
alter table public.pail_items add column if not exists memory_photo text;
alter table public.pail_items add column if not exists memory_note  text;
alter table public.pail_items add column if not exists created_at   timestamptz default now();
alter table public.pail_items add column if not exists seasons      text[] default '{}';
alter table public.pail_items add column if not exists date_start   date;
alter table public.pail_items add column if not exists date_end     date;
alter table public.pail_items add column if not exists months       text[] default '{}';


-- ---------------------------------------------------------------------
-- 3. DEFAULTS (match live exactly)
-- ---------------------------------------------------------------------

alter table public.pail_items alter column status     set default 'someday';
alter table public.pail_items alter column created_at set default now();
alter table public.pail_items alter column seasons    set default '{}';
alter table public.pail_items alter column months     set default '{}';


-- ---------------------------------------------------------------------
-- 4. NOT NULL constraints (match live: title, category, status,
--    created_at, seasons, months)
--    Each is applied only if no offending NULLs exist, so this is safe
--    and idempotent against any table state.
-- ---------------------------------------------------------------------

do $$
declare
  col       text;
  has_nulls boolean;
begin
  foreach col in array array['title','category','status','created_at','seasons','months']
  loop
    execute format(
      'select exists (select 1 from public.pail_items where %I is null)', col
    ) into has_nulls;
    if not has_nulls then
      execute format(
        'alter table public.pail_items alter column %I set not null', col
      );
    end if;
  end loop;
end $$;


-- ---------------------------------------------------------------------
-- 5. ROW LEVEL SECURITY
-- ---------------------------------------------------------------------

alter table public.pail_items enable row level security;

-- Live carries three policies on pail_items. Two are read policies that
-- overlap ("anon read" and "pail_public_read_items") — a historical
-- duplicate. Both are reproduced so this file matches live exactly.

drop policy if exists "anon read" on public.pail_items;
create policy "anon read"
  on public.pail_items
  for select
  to public
  using (true);

drop policy if exists "pail_public_read_items" on public.pail_items;
create policy "pail_public_read_items"
  on public.pail_items
  for select
  to public
  using (true);

-- Full read/write for anonymous users. pail has no auth layer; the client
-- writes directly with the anon key.
drop policy if exists "anon write" on public.pail_items;
create policy "anon write"
  on public.pail_items
  for all
  to public
  using (true)
  with check (true);


-- ---------------------------------------------------------------------
-- 6. NOT REPRODUCIBLE HERE — MANUAL STEP
-- ---------------------------------------------------------------------
-- The Memories feature uploads photos to a PUBLIC Supabase Storage bucket
-- named `memories` (path pattern: {item.id}-{timestamp}.{ext}). Storage
-- buckets and their policies are not part of the table schema and cannot
-- be created by this file. On a fresh project you must, in the Supabase
-- dashboard:
--   1. Create a bucket named `memories`
--   2. Mark it Public
--   3. Add an INSERT policy with check (true)
-- Without this, memory photo uploads fail while the rest of the app works.
-- =====================================================================
